name: Publish
on: [ push ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo $CR_PAT | docker login ghcr.io -u $CR_PAT --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_USERNAME: ${{ secrets.CR_USERNAME }}
      - name: Build and Push to GitHub Container Registry
        run: |
          export GIT_HASH=$(git rev-parse HEAD)
          HASH=$GIT_HASH make push
